### ISSUE TITLE
turn references section into slider/carousel

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool-website-2018#38]
I'd like to add more reference customers with their logos to that section. To fit more logos, please turn that section into a slider, similar to the ones we have, but:

* show as many logos as the screen width allows
* carousel mode, not slider (i.e. no rewind back to start when last item is reached)
* use right/left arrow for navigation instead of bullets
* slower animation

**Comment by neprev** [comment]
@danielnaber please check on `38-clients-slider`

**Comment by danielnaber** [comment]
Thanks, I've merged in into master and added logos, but horizontal distance between logos is not the same, even though I have cropped all images now. Please make sure the horizontal distance is always the same.

**Comment by danielnaber** [comment]
Also, once the horizontal distance issue is solved, please port the changes to https://github.com/languagetooler-gmbh/languagetool-premium-website

**Comment by neprev** [comment]
@danielnaber done and please check `38-clients-slider` branch on https://github.com/languagetooler-gmbh/languagetool-premium-website

**Comment by danielnaber** [comment]
Now the rsp24.png logo is scaled so it is bigger than is can be without being fuzzy. How to make it smaller again? `width=...` doesn't help.

![rsp24](https://user-images.githubusercontent.com/857004/40283499-5669c776-5c7f-11e8-8286-60531182445b.png)

**Comment by neprev** [comment]
@danielnaber 
Sliders divides the available space between the slides equally (they are the same width). We can do either one or the other:
-  Adjust the edges of the pictures to the slides (previously cropping the edges of the pictures) so that the gaps between them were the same. This is the current variant:
<img width="767" alt="screen shot 2018-05-27 at 21 58 28" src="https://user-images.githubusercontent.com/28347933/40588069-d41a9d60-61f9-11e8-90d4-8a0d1c98dffd.png">

- Add empty edges to the images so that they were about the same size as the others (because the proportions of the logos are different):
<img width="794" alt="screen shot 2018-05-27 at 21 58 51" src="https://user-images.githubusercontent.com/28347933/40588096-28f671ba-61fa-11e8-827b-fb01d820b031.png">

**Comment by danielnaber** [comment]
It seems to me the problem is a different one: the "rsp24" logo is scaled up only in Firefox, not in Chrome. The spaced *between* the logos are okay now.

**Comment by neprev** [comment]
@danielnaber for me they are the same:
<img width="1440" alt="screen shot 2018-05-27 at 22 42 35" src="https://user-images.githubusercontent.com/28347933/40588481-9019421e-61ff-11e8-89be-008b65a1fdbc.png">
<img width="1440" alt="screen shot 2018-05-27 at 22 42 43" src="https://user-images.githubusercontent.com/28347933/40588482-903b5bba-61ff-11e8-944b-c0adf998c0f1.png">

**Comment by danielnaber** [comment]
Strange, then it seems to be a local issue on my side. I'm closing this then.
