### ISSUE TITLE
public/js/main.js vs. resources/assets/vanilla/editor.js

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool-website-2018#9]
How are these files related, does one get automatically built from the other?

**Comment by neprev** [comment]
@danielnaber at the root of the repository you can see webpack.mix.js file. It builds (after run "npm run dev" command, for example) certain files into the public directory from which the scripts are then attached. I checked and noticed a lot of diffs in these files after the build  - i think that earlier on this project one developer used this mini builder and then another made changes directly on the public folder. In order to get this builder back to action, here needs to spend time for analyzing what's going on there, figuring out what's needed, and so on (my code in the public/main.js is literally a couple of lines, in all the rest it will be necessary to understand). Another option is to stop using this mini builder and continue to edit directly in the public

**Comment by danielnaber** [comment]
Okay, is there any good reason to use the mini builder? Editing the files directly sounds easier, or is there a drawback to that?

**Comment by neprev** [comment]
@danielnaber the builder makes sense in large projects (in particular in the single page applications) where the code is divided into many separate modules for better benchmaking and testing. I don't think that builder is needed here

**Comment by neprev** [comment]
@danielnaber I deleted the unused files from the resources/assets
